### ISSUE TITLE
How to listen to toggle changed event?

### ISSUE THREAD

**Issue by kkyr** [sindresorhus/LaunchAtLogin-Modern#3]
The older version of LaunchAtLogin has an `observable` property that can be used to listen to change events.

How can I achieve the same with this version?

**Comment by sindresorhus** [comment]
I chose not to include it here as I never used it myself, and because with macOS 13, the user can now remove it manually from being launched at login in System Settings, and there is no way to detect that (other than polling), so the property does not catch all cases.

What's your use-case for this?

**Comment by kkyr** [comment]
Needed some state to update as the user toggled the setting, though I’ve gone a different route and no longer need this use case. (Though I still think it can be useful to have.)

**Comment by sindresorhus** [comment]
Considering the mentioned limitations of it and also lack of clear use-cases, I'm not going to add this. If anyone needs this and have some convincing use-cases, please feel free to comment on this closed issue.
